# Generated by Django 3.1.6 on 2021-02-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taizhang',
            name='Commissioning_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='启用日期'),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='calibration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='检定日期'),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期日期'),
        ),
    ]
